### ISSUE TITLE
Question: Why might checks fail against Android 8 or 10?

### ISSUE THREAD

**Issue by Wedge009** [1nikolas/play-integrity-checker-app#11]
Hello.

Background: [SecurID](https://play.google.com/store/apps/details?id=com.rsa.securidapp)'s recent update (version 4.1.5.7 in September 2022) apparently has switched to using Play Integrity API for checking if a phone has been 'rooted', and they are citing your application in checking for integrity. I have three phones, none of them 'rooted' in any way, none of them have any developer switches enabled (as far as I know), Android versions 8, 10, and 11.

Both SecurID and your checker application fail against my Android 8 and 10 phones (three crosses) but seem to work okay on the Android 11 phone (three ticks). I'm not an Android developer by any means, so any clues as to why this might be happening might be helpful.

(If one looks at the recent reviews for SecurID within the last few days (19-21 September 2022) I am clearly not the only one running afoul of this new 'root' detection method.)

Appreciate any help with this. Thanks.

**Comment by 1nikolas** [comment]
Sorry but the actual checks have nothing to do with this app. The app basically asks Google if it thinks your device has been tampered (aka rooted, unlocked bootloader, etc) and displays the results. The checks themselves are done within the Google Play Services app which is pre-installed on Android phones. If the checks fail for no reason, then it seems the api has some kind of bug which only Google can fix in an upcoming Google Play Services update, I can do nothing about it.

**Comment by Wedge009** [comment]
I see, thank you for the feedback.
