### ISSUE TITLE
Check spinning forever

### ISSUE THREAD

**Issue by zgfg** [1nikolas/play-integrity-checker-app#14]
There is a special case where I click on Check and it spins forever

Two logcats are attached

It can be reproduced by using Hide My Applist v3.1.1 (module for Zygisk LSPosed):
https://github.com/Dr-TSNG/Hide-My-Applist/releases/tag/V3.1.1

Install HMA and enable in LSposed, go to App manage, enable Show system apps

Find Google Play Store (com.android.vending), open and check Enable hide - as on the screenshot).

(That's a step toward configuring HMA to detach some apps from PlayStore)

Go back, reboot

Then open PI API Checker, click on Check and it will never end, nor report an error

---

See also:
https://forum.xda-developers.com/t/hide-my-applist-a-brief-guide.4519731/post-88264113

![Screenshot_2023-03-10-12-42-11-345_com tsng hidemyapplist-edit](https://user-images.githubusercontent.com/51943147/224307438-87ec312a-8675-4dae-afd2-1b987209a3b3.jpg)

[logcat.txt](https://github.com/1nikolas/play-integrity-checker-app/files/10941615/logcat.txt)
[logcat1.txt](https://github.com/1nikolas/play-integrity-checker-app/files/10941619/logcat1.txt)

---

Looks like that Check is missing some timeout or error detection that PI API checking cannot be performed, to report an error

**Comment by 1nikolas** [comment]
Looks like a bug with the library. There is a new version, it might fix the problem. I'll try to push an app update today
