### ISSUE TITLE
Running via adb.

### ISSUE THREAD

**Issue by AppIe314** [1nikolas/play-integrity-checker-app#16]
Would it be possible to run the integrity check via adb (with the app installed)?

**Comment by 1nikolas** [comment]
the Integrity API is written in Java. Why do you need adb?

**Comment by AppIe314** [comment]
It's a niche case for those that use their phones and android TV boxes more of a Linux box. Would be cool to be able to check via CLI if play integrity passes or not. I have no idea if the Java API can be used like this.

**Comment by 1nikolas** [comment]
I can't think of any way to do this..

**Comment by AppIe314** [comment]
No worries - it's an unusual request. I appreciate you having a think about it :) 
I'll mark this as closed. Thanks!

**Comment by Displax** [comment]
> No worries - it's an unusual request. I appreciate you having a think about it :) 
> I'll mark this as closed. Thanks!

You can simply run integrity check from Play Store in settings.

**Comment by AppIe314** [comment]
> You can simply run integrity check from Play Store in settings.
This still requires the screen to be on? @Displax
