### ISSUE TITLE
Feature Request: Periodically check and notify on integrity change

### ISSUE THREAD

**Issue by Phoenix616** [1nikolas/play-integrity-checker-app#19]
It would be really nice if there was an option to periodically check the integrity and notify if a change occurs. (From passing to failing)

Edit: I guess #18 kinda would prevent that. Didn't realize this needed to check against a rate limited Google server :S

**Comment by 1nikolas** [comment]
This would be a good idea if this app didn't have a 10k/day check limit. Now it's not possible
