### ISSUE TITLE
Error Token From Google

### ISSUE THREAD

**Issue by parasgargexx20** [1nikolas/play-integrity-checker-app#22]
![Screenshot_20231117-043624_Play Integrity API Checker](https://github.com/1nikolas/play-integrity-checker-app/assets/102552831/dee78b30-107f-4b5c-98d5-16f05bb9800f)

**Comment by 1nikolas** [comment]
See #17

**Comment by parasgargexx20** [comment]
> See #17

I found an alternative route

U open playstore 

Settings 

In about category, click playstore version 7 times

In general category, developer option will appear

Click on that, click check play integrity

Done
