### ISSUE TITLE
ISSUE: Error getting token from Google

### ISSUE THREAD

**Issue by thefaizanbashir** [1nikolas/play-integrity-checker-app#28]
![Screenshot_20231201-114101](https://github.com/1nikolas/play-integrity-checker-app/assets/79439907/4842eeeb-d211-444b-9315-e91c4044e58a)

**Comment by Kris123454** [comment]
Same

**Comment by thatguywiththeboringface** [comment]
Also happening here

**Comment by luk0y** [comment]
Same

**Comment by IVAN89** [comment]
Yes the same error

**Comment by fishingwithmk** [comment]
I'm having the same problem. Not sure what happened but today I realized my Play integrity fix module stopped working when I tried to use tap to pay which led to me checking play integrity and getting the error message

**Comment by 1nikolas** [comment]
Google limits how many checks an app can do. I'll implement offline checks when I find some time (which are unlimited)

**Comment by Stardusstt** [comment]
>https://xdaforums.com/t/module-play-integrity-fix-safetynet-fix.4607985/post-89196427
<img width="540" alt="image" src="https://github.com/1nikolas/play-integrity-checker-app/assets/40061990/c586edad-ea50-4e75-9968-f6bf7ff00f3c">
