### ISSUE TITLE
Typo for Intergrity

### ISSUE THREAD

**Issue by Stillhard** [1nikolas/play-integrity-checker-app#3]
Just like to mention that you have typo in your playstore's title 'Play **Intergrity** API Checker'
Great job anyway 👍🏼

**Comment by 1nikolas** [comment]
Oh that's why it doesn't show up in search. Thank you!

**Comment by 1nikolas** [comment]
I think it's fixed now

**Comment by zgfg** [comment]
Updated to v0.4 - Aug 2, 2022

"Integrity" ok on Google Play, on the Home screen and in the package name - circled in green

Still "inteRgrity" in Settings/Apps and inside the app - boxed in red
![1](https://user-images.githubusercontent.com/51943147/185459647-3fe31e25-d995-41a1-a4ba-c49feb104e92.jpg)
![2](https://user-images.githubusercontent.com/51943147/185459699-3fde292d-5982-4d8b-b12e-7685b403b4d0.jpg)
![3](https://user-images.githubusercontent.com/51943147/185459749-a5919964-318a-4cce-9b34-3e31dccf1e20.jpg)
![4](https://user-images.githubusercontent.com/51943147/185459783-7b869d9e-fe3d-4ea1-ab5f-7874b8c1e6d7.jpg)
![5](https://user-images.githubusercontent.com/51943147/185459820-a43901fb-338e-4f56-a953-e71d28c83f97.jpg)

**Comment by 1nikolas** [comment]
https://github.com/1nikolas/play-integrity-checker-app/blob/main/app/src/main/res/values/strings.xml#L2

That's what happens when you copy paste stuff all over 😂

**Comment by 1nikolas** [comment]
Well I can't change the Play Store screenshots now my phone broke 😢
How did this slip through so many times??

**Comment by zgfg** [comment]
I actually thought  that Playstore version was out-dated (they take time to approve) and that I'd find v0.5 apk Here that was already fixed

Do you maybe have artefact/'nightly' build or so here on GitHub!?

**Comment by 1nikolas** [comment]
@zgfg v0.5 doesn't exist yet. I don't think a typo is worth a new version. Once I get a new phone and implement/fix the other issues, I'll release a new version

**Comment by zgfg** [comment]
Ok
