### ISSUE TITLE
Error getting token

### ISSUE THREAD

**Issue by Edocksil** [1nikolas/play-integrity-checker-app#31]
Version 1.1 (11) from Google Play. Default settings, no server config modifications.
Xiaomi mi 11 ultra. Latest Xiaomi.eu build on A13

**Comment by 1nikolas** [comment]
what?

**Comment by cjroma0199** [comment]
![IMG_20231205_031929.jpg](https://github.com/1nikolas/play-integrity-checker-app/assets/122694227/c1adb97a-5bbf-4aba-b5c3-e49cff68e623)

Getting this error from Redmi Note 8 Pro

**Comment by dbartussek** [comment]
I'm having the same issue. Pressing check just brings the error message "Error getting token from Google".

The body states that "the calling app is making too many requests to the API", in case that helps.

**Comment by dinamykz** [comment]
Same problem here. Latest Pixel experience android 13 on pixel 2xl.
![Screenshot_20231204-185757_Pixel Launcher](https://github.com/1nikolas/play-integrity-checker-app/assets/152933840/56782511-fbea-4f6b-90b3-ec2c927ac092)

**Comment by cizekmilan** [comment]
Same issue. Xiaomi Redmi Note 11 Pro 5G, Android 13.

**Comment by sweeneyrobb** [comment]
Same on pixel 8

**Comment by PA733** [comment]
Same on Pixel 7 Pro

**Comment by 1nikolas** [comment]
I have pushed an update to rename this error but Google hasn't approved the new update yet. This means "the app has reached the 10k tests/day limit". See #17
