### ISSUE TITLE
Persisting API error

### ISSUE THREAD

**Issue by allday5850** [1nikolas/play-integrity-checker-app#32]
When I click on the "check" I get this error every time. Even when it's the first time checking it it still gives me same error 
![Screenshot_20231205-203735](https://github.com/1nikolas/play-integrity-checker-app/assets/51069235/f410e7d4-d255-4460-ad45-abfc96bba641)

**Comment by BluCobalt** [comment]
I have the same error, even for other apps like SPIC.

**Comment by allday5850** [comment]
> > I have the same error, even for other apps like SPIC.

I just checked that one too....same results

**Comment by 1nikolas** [comment]
Google limits every app to 10k tests/day. Sorry can't do anything.. (I have updated the error message to say that but Google hasn't pushed the update yet)

See #17

**Comment by allday5850** [comment]
> okay that is fine with me. Just wanted to be sure that it wasn't something wrong from my end
