### ISSUE TITLE
App is saying to post an issue here

### ISSUE THREAD

**Issue by hectorviov** [1nikolas/play-integrity-checker-app#33]
App is saying the the API requests are being throttled, to add an issue in here.

![Screenshot_20231206-004539](https://github.com/1nikolas/play-integrity-checker-app/assets/1501713/1751c03e-2d33-4a0e-b98f-b98ef2570ee7)

**Comment by 1nikolas** [comment]
Google limits every app to 10k tests/day. Sorry can't do anything.. (I have updated the error message to say that but Google hasn't pushed the update yet)

See #17
