### ISSUE TITLE
release .apk on github repo

### ISSUE THREAD

**Issue by NewUserHa** [1nikolas/play-integrity-checker-app#36]
please release .apk on github repo

some testing devices that are inconvenient to log in play store

thanks

**Comment by 1nikolas** [comment]
It needs playstore to check that's why i didn't put the apk here

**Comment by NewUserHa** [comment]
it needs playstore to check.

but on testing devices, it does not need to log in the playstore

**Comment by NewUserHa** [comment]
and this apk is a splited apk on playstore, which is difficult to install manually and easily

**Comment by 1nikolas** [comment]
I put it on aptoide and apkpure (officially)

https://play-integrity-api-checker.en.aptoide.com/app
https://apkpure.com/play-integrity-api-checker/gr.nikolasspyr.integritycheck


Also on:
AT&T GamesHub
Beam Apps
Blu US GamesHub
Cricket GamesHub
HONOR App Market
Huawei Petal Search
JioStore
One Store
Oomph Indonesia
OPPO App Market
PWG
RuStore
Softonic
Tracfone GamesHub
UScellular GamesHub
Verizon GamesHub
Xiaomi GetApps

**Comment by NewUserHa** [comment]
thanks.

can also put on github via its release featrue
