### ISSUE TITLE
Features - link to API doc & show JSON

### ISSUE THREAD

**Issue by zgfg** [1nikolas/play-integrity-checker-app#4]
Add API documentation link to About:
https://developer.android.com/google/play/integrity/overview

For people to learn what they are testing

It would be also nice to see JSON with verdict (like in YASNAC for SafetyNet)

**Comment by 1nikolas** [comment]
The json doesn't give more info for device integrity from what it's already displayed but sure I'll add it

**Comment by zgfg** [comment]
Thanks

**Comment by zgfg** [comment]
Thanks, updated PI API Checker to v1.0 from Google Play - we have now Learn what the results mean (link to official Verdict doc) and Raw JSON response
