### ISSUE TITLE
Meaning of this

### ISSUE THREAD

**Issue by skelletR** [1nikolas/play-integrity-checker-app#6]
![IMG_20220804_215950](https://user-images.githubusercontent.com/25982450/182932382-e91d7fe6-f824-459a-8d53-cc3ed3a69f26.jpg)
meaning of all this or the first one say device, my phone Xiaomi Poco X3 NFC android 10, my other phone Sony Xperia Z5 android 7.1.1 pass the first 2 of this

**Comment by HuskyDG** [comment]
You have unlocked bootloader or your device is not certified

**Comment by 1nikolas** [comment]
Probably you have root and unlocked bootloader. My understanding for the 3 flags is:
1 -> software integrity (root etc)
2 -> device certification (if your device is certified to have playstore)
3 -> hardware integrity (bootloader)

But I can't know exactly as this is not documented well. This is all speculation

**Comment by skelletR** [comment]
Thanks, yeah I have magisk root and unlocked bootloader

**Comment by Dev0110** [comment]
I got exactly the same result.
However I can pass Safety Net, so I was thinking that Software Integrity wasn't an issue for me anymore...

**Comment by 1nikolas** [comment]
@Dev0110 Here is the deal. Apps like Google Pay started checking for the first check (MEETS_DEVICE_INTEGRITY) and they can use this as a root check basically. SafetyNet is going to get discontinued in 2024 and apps like banks will have to use Integrity API

**Comment by Dev0110** [comment]
Do you know how to pass device integrity ?
I'm a little bit confused since I'm already using root hiding techniques (shamiko) and some others tricks (universal safety net fix) that are working for Safety Net...

**Comment by 1nikolas** [comment]
@Dev0110  yes. Unfortunately, a proper solution hasn't been found yet. In the meantime there are forks of the universal safetynet fix which change your device fingerprint to show an older android version. That way, it thinks it can't do all the necessary checks and just passes (using checks for older devices). You can find lots of info on the "Magisk Google Pay" thread on xda

**Comment by Dev0110** [comment]
OK great I'll look about that on XDA !
Thanks for your help !!
