### ISSUE TITLE
Doesn't show button outline on some devices

### ISSUE THREAD

**Issue by 1nikolas** [1nikolas/play-integrity-checker-app#7]
Example
https://github.com/1nikolas/play-integrity-checker-app/issues/6#issue-1329067922

**Comment by skelletR** [comment]
> Example [#6 (comment)](https://github.com/1nikolas/play-integrity-checker-app/issues/6#issue-1329067922)

I have cropped the image

**Comment by 1nikolas** [comment]
> > Example [#6 (comment)](https://github.com/1nikolas/play-integrity-checker-app/issues/6#issue-1329067922)
> 
> I have cropped the image

Talking about the button outline

![Screenshot_20220804-212727.jpg](https://user-images.githubusercontent.com/30593419/182936526-ed1d47a3-5c81-44d0-9da2-1ecf1b23406e.jpg)

**Comment by skelletR** [comment]
![IMG_20220804_223328](https://user-images.githubusercontent.com/25982450/182937730-a191d138-d326-4306-bb43-d8c1a5db9e34.jpg)
If you have dark mode enable see it without outline but if close it for only this app is see it again

**Comment by 1nikolas** [comment]
Should be a bug of the material library. I'll look into this

**Comment by skelletR** [comment]
> Should be a bug of the material library. I'll look into this

On Android 10 Under Display - Dark mode - is this and can deselect a app if not work good with dark mode like your not see the button outline

![IMG_20220804_224346](https://user-images.githubusercontent.com/25982450/182939556-c4b58c7e-76a1-4307-b3c2-67c785ec43e4.jpg)

**Comment by 1nikolas** [comment]
> > Should be a bug of the material library. I'll look into this
> 
> On Android 10 Under Display - Dark mode - is this and can deselect a app if not work good with dark mode like your not see the button outline
> 
> ![IMG_20220804_224346](https://user-images.githubusercontent.com/25982450/182939556-c4b58c7e-76a1-4307-b3c2-67c785ec43e4.jpg)
> 

Oh so it's just miui shit

**Comment by skelletR** [comment]
> > > Should be a bug of the material library. I'll look into this
> > 
> > 
> > On Android 10 Under Display - Dark mode - is this and can deselect a app if not work good with dark mode like your not see the button outline
> > ![IMG_20220804_224346](https://user-images.githubusercontent.com/25982450/182939556-c4b58c7e-76a1-4307-b3c2-67c785ec43e4.jpg)
> 
> Oh so it's just miui shit

Yeah exactly 😂 you the only can do is warning the user who download your about don't worry and deselect your app from inside Display - Dark mode - Personalized applications. And that's is
